// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tilmpymloldupjhnkqhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbG1weW1sb2xkdXBqaG5rcWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzE3MTcsImV4cCI6MjA2Njc0NzcxN30.b688vFkC7ii_lcJ9U2AdeiAUKUxaUAXh9wbhHchhEEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);